name: Install

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
    steps:
      - uses: actions/checkout@v4

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Install OpenGL and SFML
        run: |
          ./vcpkg/vcpkg install opengl sfml
          ./vcpkg/vcpkg integrate install

      - uses: actions/cache@v4
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: build and install library
        run: |
          cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON
          sudo cmake --build build --target install --verbose
          rm -rf build

      - name: configure
        run: cmake -Stest -Bbuild -DTEST_INSTALLED_VERSION=1 -DCMAKE_VERBOSE_MAKEFILE=ON

      - name: build
        run: cmake --build build --config Debug -j4 --verbose

      - name: test
        run: |
          cd build
          ctest --build-config Debug --verbose
