name: Install

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: build and install library
        run: |
          cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local
          sudo cmake --build build --target install
          echo "Installed files:"
          sudo find /usr/local/include/hobby -type f
          rm -rf build

      - name: configure tests
        run: |
          cmake -Stest -Bbuild/test -DTEST_INSTALLED_VERSION=1 -DCMAKE_PREFIX_PATH=/usr/local
          echo "Include directories during configure:"
          cmake --system-information | grep "CMAKE_CXX_FLAGS"
          find /usr/local/include/hobby

      - name: build tests with diagnostics
        run: |
          cmake --build build/test --config Debug -j4 --verbose

      - name: run tests
        run: |
          cd build/test
          ctest --build-config Debug
