name: Style

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install format dependencies
        run: pip3 install clang-format==16.0.6 cmake_format==0.6.13 pyyaml

      - name: Check cmake format
        run: |
          cmake-format -c .cmake-format.yaml CMakeLists.txt
          cmake-format -c .cmake-format.yaml test/CMakeLists.txt
          cmake-format -c .cmake-format.yaml standalone/CMakeLists.txt

      - name: Check clang format
        run: |
          find . -name "*.cpp" -o -name "*.hpp" | xargs clang-format -i --dry-run --Werror
